trigger: none

pool:
  name: "linuxpool"
  demands:
    - Agent.Name -equals linuxagent

steps:

# Step 1: Build the Docker image using the Dockerfile in your repository
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'  # Path to your Dockerfile (adjust if needed)
    tags: '$(Build.BuildId)'  # Tag the image with the build ID (or use 'latest' if preferred)

# Optionally, you can add more steps to test the image locally or inspect it (optional)
# Example: Verify the image is built (this will run `docker images` as a sanity check)
- script: |
    docker images
  displayName: 'List Docker Images'
